import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
// import Head from "next/head";


// import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, authModal }: { children: React.ReactNode; authModal: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <Providers> */}
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=clash-display@1&display=swap" rel="stylesheet"></link>
      </head>
      <body className={`${inter.className}`}>
        <Navbar></Navbar>
        {authModal}
        {children}
        <Footer></Footer>
      </body>
      {/* </Providers> */}
    </html>
  );
}
